module Main where

-- generated by cabal at build time
import Paths_tubular (version)

import Snap
-- import Dhall
-- import Options.Applicative

main :: IO ()
main = do
  -- get command-line options
  -- get config file options
  -- print debug info
  putStrLn ("Tubular version " ++ show version)
  -- serve http
  let config = defaultConfig
  httpServe config snapMain

snapMain :: Snap ()
snapMain = do
  return ()
